# Assignment-2

This notebook contains the coding questions to test the proficiency in `NumPy` library of python.

### Date: 7th December, 2025

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the questions in the notebook and save it.
- Rename the file as `Assignment-02-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-02-Dipika_Chopra.ipynb`.
- Upload the solved notebook in your github repo under the folder **Assignment-2**.
- Upload the solved notebook in the google drive location: https://drive.google.com/drive/folders/163Prhhe78pDrm7EQJmU6puuRQJ2agxzl?usp=drive_link 

<h3><span style="color:red"> Deadline: 21st December, 2025 </span></h3>

In [1]:
import numpy as np

## Problem: 1
Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [2]:
# Write your code here
subdivision =  np.linspace(-1.3, 2.5,64)
print (subdivision)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


## Problem: 2

Generate an array of length $3n$ , filled with the cyclic pattern 1, 2, 3. Where $n$ is a natural number.

In [5]:
# Write your code here
n=7
pattern_list= np.array([i for i in range(7)])
cyclic_pattern = np.tile(pattern_list,3)
print(cyclic_pattern)

[0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6]


## Problem: 3
Create an array of the first $n$ odd integers. $n$ is a natural number input from user.

In [6]:
# Write your code here
n = int(input("Enter a number to calculate odds : "))
odd_numbers = np.arange(1,2*n, 2)
print (odd_numbers)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


## Problem: 4

Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [7]:
# Write your code here

inner_array = np.zeros((10,10),dtype=int)
padded_array= np.pad(inner_array,pad_width=1,constant_values=1)
print(padded_array)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


## Problem: 5

Create an 8 x 8 array with a checkerboard pattern of zeros and ones.

In [ ]:
# Write your code here



## Problem: 6

Create an array $x$ with 100 points in the interval $[-1,1]$ (the points must be uniformly spaced). Then create another array $y$. 

Where $y = x^2 sin(x^2) + x$. 

Try to plot $y$ vs $x$ using matplotlib.

In [ ]:
# Write your code here



## Problem: 7 
Create a function which creates an $n×n$ array with $(i , j)$ -entry equal to $i+ j$

In [ ]:
# Write your code here



# Problem: 8
Evaluate $cos$ and $sin$ on the interval $[0,1]$  with 1000 points and then stack the results into a tall array with rows being the $(cos(x),sin(x))$ entries.

In [4]:
# Write your code here


# Problem: 9

Create a random $3×5$ array using the `np.random.rand(3 ,5)` function and compute: the sum of all the entries, the sum of the rows, and the sum of the columns.

In [ ]:
# Write your code here



## Problem: 10

Create a random $5×5$ array using the function `np.random.rand(5, 5)`. Then sort the rows according to the second column.

In [ ]:
# Write your code here

